[phases.setup]
nixPkgs = ['nodejs', 'python3', 'gcc', 'gnumake', 'pkg-config', 'libtool', 'autoconf', 'automake', 'ffmpeg']

[phases.install]
cmds = ['npm install --legacy-peer-deps']

[start]
cmd = 'npm start' 